version: '3.3'

services:
  app:
    image: geekinside/orangesocialsite:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your_secret_key
      - JWT_SECRET_KEY=your_jwt_secret_key
      - DATABASE_URL=postgresql://postgres:your_password@db:5432/twitter_clone_db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=twitter_clone_db

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

